# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('urlpost', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=100)),
                ('searchtext', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchs.Search'),
        ),
    ]
