# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='artist',
            field=models.CharField(default='Unknown', max_length=500),
        ),
    ]
