# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchs', '0002_image_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.CharField(default='Unknown', max_length=1000),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumb',
            field=models.CharField(default='Unknown', max_length=1000),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(default='Unknown', max_length=1000),
        ),
        migrations.AlterField(
            model_name='image',
            name='urlpost',
            field=models.CharField(default='Unknown', max_length=1000),
        ),
    ]
