# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchs', '0003_auto_20160329_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='artist',
            field=models.CharField(blank=True, default='Unknown', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.CharField(blank=True, default='Unknown', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumb',
            field=models.CharField(blank=True, default='Unknown', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(blank=True, default='Unknown', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='urlpost',
            field=models.CharField(blank=True, default='Unknown', max_length=1000, null=True),
        ),
    ]
