# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-16 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchs', '0006_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.CharField(blank=True, default='None', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='apikey',
            field=models.CharField(default='', max_length=500),
        ),
    ]
