# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-04 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchs', '0007_auto_20160716_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='working',
            field=models.BooleanField(default=True),
        ),
    ]
