# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-03 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchs', '0008_search_working'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(default='Error', max_length=500)),
            ],
        ),
    ]
